In [1]:
from pyroaring import BitMap
import pandas as pd

def size_of_bitmap(start: int, length: int) -> int:
    bm = BitMap()
    for i in range(start, start + length):
        bm.add(i)
    return len(bm.serialize())

cases_contiguous_df = pd.DataFrame([
    {
        'Start': 0,
        'Length': 10
    },
    {
        'Start': 0,
        'Length': 100
    },
    {
        'Start': 0,
        'Length': 1000
    },
    {
        'Start': 1000,
        'Length': 10
    },
    {
        'Start': 1000,
        'Length': 100
    },
    {
        'Start': 1000,
        'Length': 1000
    },
    {
        'Start': 1000000,
        'Length': 10
    },
    {
        'Start': 1000000,
        'Length': 100
    },
    {
        'Start': 1000000,
        'Length': 1000
    }
])

cases_contiguous_df['Bitmap size'] = cases_contiguous_df.apply(lambda x: size_of_bitmap(x['Start'], x['Length']), axis='columns')
cases_contiguous_df

     Start  Length  Bitmap size
0        0      10           36
1        0     100          216
2        0    1000         2016
3     1000      10           36
4     1000     100          216
5     1000    1000         2016
6  1000000      10           36
7  1000000     100          216
8  1000000    1000         2016

In [2]:
import random

cases_random_df = pd.DataFrame([
    {
        'Max': 1000,
        'Length': 10
    },
    {
        'Max': 1000,
        'Length': 100
    },
    {
        'Max': 1000,
        'Length': 1000
    },
    {
        'Max': 1000000,
        'Length': 10
    },
    {
        'Max': 1000000,
        'Length': 100
    },
    {
        'Max': 1000000,
        'Length': 1000
    },
    {
        'Max': 1e9,
        'Length': 1e4
    },
    {
        'Max': 1e9,
        'Length': 1e5
    },
    {
        'Max': 1e9,
        'Length': 1e6
    },
    {
        'Max': 4e9,
        'Length': 1e7
    },
    {
        'Max': 4e9,
        'Length': 1e8
    },
])

def size_of_bitmap_random(max: int, length: int) -> int:
    bm = BitMap(random.sample(range(int(max)), int(length)))
    return len(bm.serialize())

cases_random_df['Bitmap size'] = cases_random_df.apply(lambda x: size_of_bitmap_random(x['Max'], x['Length']), axis='columns')
cases_random_df

             Max       Length  Bitmap size
0   1.000000e+03         10.0           36
1   1.000000e+03        100.0          216
2   1.000000e+03       1000.0           15
3   1.000000e+06         10.0           84
4   1.000000e+06        100.0          336
5   1.000000e+06       1000.0         2136
6   1.000000e+09      10000.0        79224
7   1.000000e+09     100000.0       321904
8   1.000000e+09    1000000.0      2122080
9   4.000000e+09   10000000.0     20488296
10  4.000000e+09  100000000.0    200488296